global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'easyrx-api'
    static_configs:
      - targets: ['easyrx-api:3000']
    metrics_path: '/metrics'
    
  - job_name: 'postgres'
    static_configs:
      - targets: ['easyrx-db:9187']
    
  - job_name: 'redis'
    static_configs:
      - targets: ['easyrx-redis:9121']
